Feat/scout 257 live video
scoutmaker/scoutmaker-backend-v2-nest pull request #129
Opened 2022-11-09 23:19 UTC by dejwi

### Task Description
[SCOUT-257](https://playmakerpro.atlassian.net/browse/SCOUT-257?atlOrigin=eyJpIjoiNGNhOWI5YWFhY2Y2NDc5NzlmNjNjMDYxYzdlN2ExM2EiLCJwIjoiaiJ9)

- adjusted `notes` `reports` `matchAttendance` for observation type
- added observation type& method for getting it at `matches`

if there was a way to do it with prisma I'm sorry I couldn't find anything related

2022-11-12 13:00 UTC, jakubfiglak requested changes
Good work 💯 

There're some changes requested though, please see my comments.

And about extracting information wether the match has been watched live, on video or both ways, I'm not a biggest fan of the solution we have right now but I did some research and I also can't see anything closer to the database level. It looks like we need to calculate it ourselves, just as you did. I asked on Prisma Slack, they told me it's the only way. I've seen a promising feature in their docs though:

https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#filter-the-relation-count

Looks like you can filter on `count` but it seems like you cannot query for more than one `count` on one relation, which is what would solve our problem.

Anyway, I'm gonna ask my backend engineer colleague at work on Monday for some help, and if I get any useful tips, I'll get back to you.

2022-11-14 16:00 UTC, dejwi commented on src/modules/notes/dto/find-all-notes.dto.ts
> +  observationType?: ObservationTypeEnum;
I think we don't need it because every observation has observationType so just not filtering by it, is exactly the same as filtering by `BOTH`

2022-11-14 16:25 UTC, dejwi commented on prisma/migrations/20221108225005_observation_type_default_and_added_to_match_attendance/migration.sql
> +ALTER TABLE "Report" ALTER COLUMN "observationType" SET DEFAULT E'VIDEO';
![image](https://user-images.githubusercontent.com/80927085/201712602-0fc9eb1b-4ed9-4f84-a4ab-fbeb0b8824e4.png)
yes?

2022-11-14 17:01 UTC, dejwi commented
is this what you meant with `CreateMatchAttendanceDto` ? Or do you want to move all data into body

2022-11-15 07:52 UTC, jakubfiglak commented
> is this what you meant with `CreateMatchAttendanceDto` ? Or do you want to move all data into body

I wanted to move everything to body, just as in every other module

2022-11-15 07:55 UTC, jakubfiglak commented on src/modules/matches/matches.service.ts
> +      Match & { notes: ObservationTypeOnly; reports: ObservationTypeOnly },
What's the purpose of this generic? I mean, I don't have anything against generics, I just don't understand why you structured this one the way you did, can you explain?

2022-11-15 12:32 UTC, dejwi commented on src/modules/matches/matches.service.ts
> +      Match & { notes: ObservationTypeOnly; reports: ObservationTypeOnly },
it's there to keep our types from any prisma include that we use in return type without specifying too much
maybe you have a better solution

`matches controller` without generic
![image](https://user-images.githubusercontent.com/80927085/201920364-2fd72c66-3232-411a-811a-68166b59a849.png)

2022-11-15 12:51 UTC, jakubfiglak commented on src/modules/matches/matches.service.ts
> +      Match & { notes: ObservationTypeOnly; reports: ObservationTypeOnly },
Alright, but why `T & Match & <other_stuff>` then? I think you could do something like this:

```
private fillObservationType<
    T extends { notes: ObservationTypeOnly; reports: ObservationTypeOnly },
  >(match: T): T & { observationType: ... }
```

And perhaps you might find this part of the docs helpful

https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/operating-against-partial-structures-of-model-types#solution-1

2022-11-15 12:56 UTC, dejwi commented
can match attendances be like that? I think we don't need matchId to leave the match same as we don't need it to get active one

2022-11-15 13:01 UTC, jakubfiglak commented
> can match attendances be like that? I don't think we need matchId to leave the match same as we don't need it to get active one

You're right, good catch. It looks okay

2022-11-19 13:08 UTC, jakubfiglak requested changes
We're getting there, just some naming issues and that's it.

Don't worry about this migrations, I'd rather keep all of them than clear our dev database again.

2022-11-19 13:08 UTC, jakubfiglak commented on src/modules/match-attendances/match-attendances.controller.ts
> +  @Patch()
We need to name this endpoint somehow so that it is obvious that it's purpose is to leave the currently active match. As it is right now, it's just a PATCH  `/match-attendances` endpoint with no parameters, there's no way someone from outside will know how to use it. In fact, we will forget in a week 🤣

2022-11-19 13:08 UTC, jakubfiglak commented on src/modules/match-attendances/match-attendances.service.ts
> +  async goToMatch(
I'd rename this to `create`

2022-11-19 13:08 UTC, jakubfiglak commented on src/modules/match-attendances/match-attendances.service.ts
> +  leaveTheMatch(userId: string) {
I'd rename this to something like `leaveActiveMatch` or something like that

2022-11-20 11:15 UTC, dejwi commented on src/modules/match-attendances/match-attendances.controller.ts
> +  @Patch()
yeah at first I got lost looking into this😅

2022-11-20 11:17 UTC, dejwi commented
what about someting like this?
in docs:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/80927085/202899084-bddf24e5-3ba4-49cf-8cd6-224c012458c1.png">

2022-11-21 18:33 UTC, jakubfiglak requested changes
Sorry, still something 🤣

2022-11-21 18:33 UTC, jakubfiglak commented on src/modules/match-attendances/match-attendances.service.ts
> +  async setActiveMatch(
Naaah, it's just `create`. We are not setting active match here, we are creating `match-attendance`. Let's stick with `create` name for this, there's no reason why it should be called any different compared to all other services in the app.

2022-11-21 18:33 UTC, jakubfiglak commented on src/modules/match-attendances/match-attendances.controller.ts
> +  @Patch()
I feel like the changes you suggested in the docs are not enough. I mean, we can have descriptions in swagger, there's no harm in that, but I think the endpoint path should be descriptive as well. 

```suggestion
  @Patch('leave-active')
```

2022-11-21 21:38 UTC, dejwi commented on src/modules/match-attendances/match-attendances.service.ts
> +  async setActiveMatch(
yeah maybe that would be reasonable:p

2022-11-22 07:47 UTC, jakubfiglak approved these changes

2022-11-22 16:20 UTC, merged