Feat/scout 259 dashboard
scoutmaker/scoutmaker-backend-v2-nest pull request #137
Opened 2022-11-19 12:25 UTC by dejwi

### Task Description
[SCOUT-259](https://playmakerpro.atlassian.net/browse/SCOUT-81?atlOrigin=eyJpIjoiMTU4OWJlMDQxZjk2NDI4ZGJjODk4Y2M4NTZhZDlhYjUiLCJwIjoiaiJ9)

<sub>includes commits from some merges that were needed for testing(mb not user subs)</sub>
dashboard module
- if you have better properties names idea LMK
- misses checking subscriptions in organizations list + top players (Jacek sql master)
- in scout organization players count is 0 because of our team endDate null issue

Prior to your possible question I included User data from request in DashboardDto to make less requests at frontend and make life little easier at no cost

As you'll see types are EH but I had to match them somehow, in other endpoints you didn't exactly match dtos and returned data but here as I'm assigning everything to one typed object typescript screams at me

2022-11-19 14:07 UTC, jakubfiglak requested changes
This is super hard to read. Please try and refactor `dashboard.service` - try and split it to smaller methods maybe, definitely do not use `this.prisma.anything` directly here, create related service methods.

I got tired in the middle of this but I can see that in the dto, you return `reports?: number`. I assume this is reports count, so it should be named `reportsCount`. The same applies for every other count. When I see property named `reports`, I automatically assume I'm gonna get array of data, not just a random number.

2022-11-19 14:07 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      );
You see what I mean with all these complaining about using `this.prisma.blablabla` directly? This is how it should be done - inject a service and use a service method

2022-11-19 14:17 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +  }
Oh I totally missed that

2022-11-20 12:14 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +  private async getScoutData(user: CurrentUserDto) {
no, you have roles line above it

2022-11-20 12:15 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +  private async getPMData(user: CurrentUserDto) {
developed my new blazing fast javascript framework🤧

2022-11-20 12:25 UTC, dejwi commented
what about names like that? I think it's a nice compromise. You've said that you got tired reading halfway into that, try reading it with `recentRoleScopeReportsCountPromise recentRoleScopeNotesCountPromise recentRoleScopeMatchesCountPromise` and so on😂

2022-11-20 12:41 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +      }),
Yeah so for now we only return organizations that we share data with via acls. 
In this query we get organizations that have any acl tied to requesting user. 
Includes only acls that we care about so down below where we extract shared matches count we don't have to iterate through acls that are not tied to requesting user.

```js
// only acls for now
    data.organizations = sharedAclOrganizations.map((org) => {
      const observedMatchesIds = new Set<string>(); // <- stores only unique values

      // with that include we iterate only through acls with note created by requesting user
      org.noteAccessControlList.forEach((noteAce) => {
        if (noteAce.note.matchId) observedMatchesIds.add(noteAce.note.matchId);
      });

      // with that include we iterate only through acls with report created by requesting user
      org.reportAccessControlList.forEach((reportAce) => {
        if (reportAce.report.matchId)
          observedMatchesIds.add(reportAce.report.matchId);
      });
      return { name: org.name, sharedMatchesCount: observedMatchesIds.size };
    });

    return data;
  }
```

2022-11-22 19:33 UTC, jakubfiglak requested changes
I know this task is a little bit complicated since the service we need to create combines the data from a lot of places but I think we can do better in terms of structuring our code. Let's take `getPrivilegedUserData` (ADMIN/PLAYMAKER-SCOUT/PLAYMAKER-SCOUT-MANAGER) as an example. We should aim for a structure like this:

```
  getPrivilegedUserData(user: CurrentUserDto) {
    const createdReportsCount = getReportsCountForUser(user.id)
    const createdReportsPercentage = getCreatedReportsPercentageForUser(user.id)

    const createdNotesCount = getNotesCountForUser(user.id)
    const createdNotesPercentage = getCreatedNotesPercentageForUser(user.id)
    
    const observedMatches = getObservedMatchesCountForUser(user.id)
    const observedMatchesPercentage = getObservedMatchesPercetageForUser(user.id)

    // potentially some other stuff
  }
 ```

This is just pseudo code but hopefully it explains what I mean. This way, whoever is reading that code, knows at a glance what exactly is being return from this function, and if they are interested, they can always analyze it piece by piece.

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    });
```suggestion
    const totalUserReportsPromise = this.reportsService.getCount({ accessFilters: { authorId: user.id } })
```

Why don't we do it like this?

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    });
The same for all of this, I don't see any reason for creating another level of abstraction with all these functions. You can destructure for example `const { getCount } = this.matchesService;` if you want to save yourself some typing.

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      this.prisma.organization.findMany({
`this.prisma` direct call

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      }),
Yeah, you see, this is why this kind of things should be extracted to separate functions. This where clause is a little bit too specific and too hard to understand to just live here. How about creating a private method inside `dashboard.service`, something like `getOrganizationsForScout` or something like that?

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +  }
Whatever this function is doing, it should be extracted as well

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    const topNotesPromise = this.prisma.note.findMany({
`this.prisma` call

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    const topReportsPromise = this.prisma.report.findMany({
`this.prisma` call

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/matches/matches.service.ts
> +    accessFilters?: Prisma.MatchWhereInput;
Isn't one argument enough here? Renamed to `filters` so it's more generic?

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/notes/notes.service.ts
> +  getCount(accessFilters: Prisma.NoteWhereInput) {
```suggestion
  getCount(filters: Prisma.NoteWhereInput) {
```

These are not necessarily ACCESS filters, are they?

2022-11-22 19:33 UTC, jakubfiglak commented on src/modules/players/players.service.ts
> +  }
This is the third in a row `getCount` function I'm reading, after one in `matches.service` and one in `notes.service`, and each of them is slightly differently written. Why is that?

2022-11-22 22:27 UTC, dejwi commented on src/modules/players/players.service.ts
> +  }
Where we had already separated `generateWhereClause` I went with the same way as in findAll/getList

2022-11-27 23:06 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +    });
doesn't work, `const getReportsCount = this.reportsService.getCount` too :(

2022-11-27 23:16 UTC, dejwi commented
do you REALLY want to separate EVERYTHING like in your pseudocode example? Most of the data calls are already pretty short and it would add a lot of boilerplate

2022-11-27 23:20 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +  private async getSharedToOrganizations(
I got a bit lost in prisma type landia(due to errors) so just please double check that function:))

2022-11-29 16:41 UTC, jakubfiglak reviewed
This looks MUCH better now, great job 🚀 

I'm willing to approve this PR as soon as we're aligned on what do we do with the organizations query (raw sql thing)

2022-11-29 16:41 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      //
Can we remove this?

2022-11-29 16:41 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      user,
I still don't get why we're returning user here, can we get rid of that?

2022-11-29 16:41 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    return await this.notesService.findAll(
```suggestion
    return this.notesService.findAll(
```

2022-11-29 16:41 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +    return await this.reportsService.findAll(
```suggestion
    return this.reportsService.findAll(
```

2022-11-29 16:41 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +  }
Let's not spend too much time on this - we don't use `acl` related features right now and we need to find a way to get this data based on subscriptions. We need to focus on that. Where are we with this part, have you agreed with Jacek that we're gonna use raw sql for this?

2022-11-29 16:41 UTC, jakubfiglak commented on src/utils/helpers.ts
>  }
```suggestion
export function calculatePercentage(value: number, base: number) {
  return parseFloat(((value / base) * 100).toFixed(2));
}
```

Let's rename these arguments since we're switching to more generic solution now

2022-11-29 17:56 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +      user,
it's used in the frontend, like here we select which data to return here based on some conditions, there we display the correct layout based on like the same conditions, so additional user data calls are unnecessary and with react-query there would be a lot of them

2022-11-29 18:06 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      user,
But we know who the user is on the frontend without that. What user information do you use on the frontend for this feature? This service shouldn't return user data.

2022-11-30 16:52 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +      user,
user role and if he's in a organization

2022-11-30 17:13 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      user,
Yeah, we know the user role without it. And if we need info wether user is in an organization or not, we can return it from this controller https://github.com/scoutmaker/scoutmaker-backend-v2-nest/blob/6dc329d5d542e088100f94ea92b553fce9ce7af9/src/modules/auth/auth.controller.ts#L92

But think it shouldn't be necessary - `dashboard` service decides what data it should return to the client. Why do you need to check user role and the other condition on the client side for the second time? Frontend should just render whatever it gets from the backend.

2022-12-01 08:34 UTC, jakubfiglak requested changes
One last step - please remove `user` from returned objects and we're all good

2022-12-01 08:34 UTC, jakubfiglak commented on src/modules/dashboard/dashboard.service.ts
> +      user,
Another user return

2022-12-05 22:48 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +      user,
nooo, if you check the ticket, we have separate layouts for roles/organization so we have to check that in the frontend

2022-12-05 22:53 UTC, dejwi commented on src/modules/dashboard/dashboard.service.ts
> +      user,
so you're sure about switching to separate hook?

2022-12-11 13:43 UTC, jakubfiglak approved these changes

2022-12-21 23:11 UTC, dejwi commented
you've already approved this but please review new changes

2022-12-27 06:57 UTC, jakubfiglak approved these changes

2022-12-27 22:06 UTC, merged